#!/usr/bin/env ruby

require 'tty-prompt'

def pdf_dir_and_name_without_extension(pdf_path)
  pdf_dir = File.dirname(pdf_path)
  pdf_name_without_extension = File.basename(pdf_path, ".pdf")

  [pdf_dir, pdf_name_without_extension]
end

font_path = <<-FONT_PATH
/usr/lib/X11/fonts/Type1Adobe
/usr/lib/DPS/outline/decwin
/usr/lib/X11/fonts/type1.st/typefaces
/usr/lpp/DPS/fonts/outlines
/usr/lpp/X11/lib/X11/fonts/Type1
/usr/lpp/X11/lib/X11/fonts/Type1/DPS
/NextLibrary/Fonts/outline
/usr/lib/DPS/outline/base
/usr/lib/X11/fonts/Type1
/usr/openwin/lib/X11/fonts/Type1/outline
/usr/openwin/lib/X11/fonts/F3/
/usr/openwin/lib/X11/fonts/F3bitmaps/
/usr/openwin/lib/X11/fonts/Type1/
/usr/openwin/lib/X11/fonts/Speedo/
/usr/openwin/lib/X11/fonts/misc/
/usr/openwin/lib/X11/fonts/75dpi/
/usr/openwin/lib/X11/fonts/100dpi/
/usr/openwin/lib/X11/fonts/Xt+/
/usr/dt/config/xfonts/C
/usr/dt/config/xfonts/C
/usr/local/share/lib/amaya/amaya-1.0b/Thot/fonts/
/usr/local/share/lib/X11/fonts/100dpi
/usr/local/share/lib/X11/fonts/European
/usr/local/share/lib/X11/fonts/Ethiopic
/usr/local/share/lib/X11/fonts/Asian
/usr/local/share/lib/X11/fonts/waterloo
/usr/local/share/lib/X11/fonts/Korean
/usr/local/share/lib/X11/fonts/Chinese
/usr/local/share/lib/X11/fonts/Chinese-BIG
/usr/local/share/lib/X11/fonts/Japanese
/usr/local/share/lib/X11/fonts/Japanese-BIG
/usr/local/share/lib/X11/fonts/Misc
~/Library/Fonts
/Library/Fonts
/Network/Library/Fonts
/System/Library/Fonts
/Volumes/C/Windows/Fonts
.
FONT_PATH
font_path = font_path.split(/\r?\n/).join(":")

tty_prompt = TTY::Prompt.new
pdf_password = tty_prompt.ask("Please enter the PDF's password:")
pdf_path = ARGV[0]
pdf_dir, pdf_name_without_extension = pdf_dir_and_name_without_extension(pdf_path)
unlocked_pdf_path = File.join(pdf_dir, "#{pdf_name_without_extension} Unlocked.pdf")

system(%Q(gs -dSAFER -dBATCH -dNOPAUSE -sDEVICE=pdfwrite -sFONTPATH="#{font_path}" -sPDFPassword=#{pdf_password} -dPDFSettings=/prepress -dPassThroughJPEGImages=true -sOutputFile="#{unlocked_pdf_path}" "#{pdf_path}"))

puts "Password removed successfully."
